// <auto-generated />
namespace CFO.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class identity_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identity_int));
        
        string IMigrationMetadata.Id
        {
            get { return "202104141916116_identity_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
